import httpx
import json
import base64
from typing import Dict, Any
import os


class GitHubService:
    def __init__(self, client_id: str, client_secret: str, repo_owner: str, repo_name: str):
        self.client_id = client_id
        self.client_secret = client_secret
        self.repo_owner = repo_owner
        self.repo_name = repo_name
        self.api_base = "https://api.github.com"
    
    async def create_contribution_pr(
        self,
        problem_id: int,
        problem_title: str,
        language: str,
        code: str,
        contributor_github: str,
        runtime: str = None,
        memory: str = None
    ) -> Dict[str, Any]:
        """
        Create a Pull Request for a new solution contribution
        This requires a GitHub App token or PAT (Personal Access Token)
        """
        # For now, return mock data
        # In production, you'll need to:
        # 1. Fork the repo (or use the contributor's fork)
        # 2. Create a new branch
        # 3. Update final_database.json with the new solution
        # 4. Create commit
        # 5. Create pull request
        
        # This is a simplified version - you'll need proper GitHub authentication
        pr_data = {
            "number": 999,  # Mock PR number
            "url": f"https://github.com/{self.repo_owner}/{self.repo_name}/pull/999",
            "title": f"Add {language} solution for Problem #{problem_id}: {problem_title}",
            "body": self._generate_pr_body(problem_id, problem_title, language, runtime, memory, contributor_github)
        }
        
        return pr_data
    
    def _generate_pr_body(
        self,
        problem_id: int,
        problem_title: str,
        language: str,
        runtime: str,
        memory: str,
        contributor: str
    ) -> str:
        """Generate PR description"""
        body = f"""## 🎉 New Solution Contribution

**Problem:** [#{problem_id}: {problem_title}](https://leetcode.com/problems/{problem_title.lower().replace(' ', '-')}/)
**Language:** {language}
**Contributor:** @{contributor}

### Performance Metrics
"""
        if runtime:
            body += f"- **Runtime:** {runtime}\n"
        if memory:
            body += f"- **Memory:** {memory}\n"
        
        body += """
### Contribution Details
- ✅ Solution verified on LeetCode
- ✅ Automated PR created via LeetBuddy extension
- ✅ Ready for review

---
*This PR was automatically generated by [LeetBuddy](https://github.com/yourusername/leet-buddy) 🚀*
"""
        return body
    
    async def get_user_info(self, access_token: str) -> Dict[str, Any]:
        """Get GitHub user information"""
        async with httpx.AsyncClient() as client:
            response = await client.get(
                f"{self.api_base}/user",
                headers={
                    "Authorization": f"token {access_token}",
                    "Accept": "application/vnd.github.v3+json"
                }
            )
            response.raise_for_status()
            return response.json()
